name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: CrewAI Test
      id: crewai-test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 100
        setup-command: pip install -r requiremnts.txt
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CREWAI-TEST_RESULTS: "${{steps.crewai-test.outputs.result}}"
      with:
        runners: crewai-test
